spring.application.name=crypto-broker

# Dane klastra
zeebe.client.cloud.cluster-id=1a8dffde-9f4d-47cb-b7b7-a60426f418d2
zeebe.client.cloud.region=fra-1

# Dane API - upewnij si?, ?e nie ma tu spacji na ko?cu linii!
zeebe.client.cloud.client-id=MNrMXZ.vr3CBjpqQcejLG8eicu-F3dRW
zeebe.client.cloud.client-secret=I_36srwJrrv~un2DN_NmINF7g8aJwqZRjT8Cprnpl0cQIj.NyOGQRgOBmdtaT8k~

# Konfiguracja Camunda
camunda.client.mode=saas
zeebe.client.worker.default-type=default

# Wydajno??
spring.threads.virtual.enabled=true